spring:
  application:
    name: SegAProj
  datasource:
    url: jdbc:postgresql://localhost:5432/segaproj_db
    dbname: segaproj_db
    username: postgres
    password: rootqwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: = true
server:
  port: 9090